# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import reader_pb2 as reader__pb2


class ReaderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReadFile = channel.unary_unary(
        '/grpcreader.Reader/ReadFile',
        request_serializer=reader__pb2.ReadRequest.SerializeToString,
        response_deserializer=reader__pb2.ReadReply.FromString,
        )


class ReaderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ReadFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReaderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReadFile': grpc.unary_unary_rpc_method_handler(
          servicer.ReadFile,
          request_deserializer=reader__pb2.ReadRequest.FromString,
          response_serializer=reader__pb2.ReadReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'grpcreader.Reader', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
