# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reader.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reader.proto',
  package='grpcreader',
  syntax='proto3',
  serialized_pb=_b('\n\x0creader.proto\x12\ngrpcreader\"\x1f\n\x0bReadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1c\n\tReadReply\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2F\n\x06Reader\x12<\n\x08ReadFile\x12\x17.grpcreader.ReadRequest\x1a\x15.grpcreader.ReadReply\"\x00\x42\x30\n\x19nex3z.examples.grpcreaderB\x0bReaderProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='grpcreader.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='grpcreader.ReadRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=59,
)


_READREPLY = _descriptor.Descriptor(
  name='ReadReply',
  full_name='grpcreader.ReadReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='grpcreader.ReadReply.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['ReadReply'] = _READREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), dict(
  DESCRIPTOR = _READREQUEST,
  __module__ = 'reader_pb2'
  # @@protoc_insertion_point(class_scope:grpcreader.ReadRequest)
  ))
_sym_db.RegisterMessage(ReadRequest)

ReadReply = _reflection.GeneratedProtocolMessageType('ReadReply', (_message.Message,), dict(
  DESCRIPTOR = _READREPLY,
  __module__ = 'reader_pb2'
  # @@protoc_insertion_point(class_scope:grpcreader.ReadReply)
  ))
_sym_db.RegisterMessage(ReadReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031nex3z.examples.grpcreaderB\013ReaderProtoP\001\242\002\003HLW'))

_READER = _descriptor.ServiceDescriptor(
  name='Reader',
  full_name='grpcreader.Reader',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=91,
  serialized_end=161,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReadFile',
    full_name='grpcreader.Reader.ReadFile',
    index=0,
    containing_service=None,
    input_type=_READREQUEST,
    output_type=_READREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_READER)

DESCRIPTOR.services_by_name['Reader'] = _READER

# @@protoc_insertion_point(module_scope)
